# Defines module properties and dependencies for Bzlmod
module(
    name = "trie_pybind11",
    version = "0.0.1",
    bazel_compatibility = [">=6.0.0"],
)
bazel_dep(name = "platforms", version = "0.0.11")  

# --- Bzlmod Python Dependency ---
bazel_dep(name = "rules_python", version = "1.3.0")

# --- Bzlmod Pybind11 Dependency ---
bazel_dep(name = "pybind11_bazel", version = "2.13.6")

# --- Bzlmod C++ Dependency ---
bazel_dep(name = "rules_cc", version = "0.1.1")
